#!/bin/sh

set -e

. ./build_config

build_type="$1"

if [ -z "${build_type}" ]
then
    echo "No build type!"
fi

YY_INSTALL_DIR="${HOME}/code/cpp/build"
YY_TP_DIR="${HOME}/code/tp"

. ./build_config
. ./build_cmake_config ${build_type}

build_target() {
    local build_dir=$1

    cd ${build_dir}
    if [ -f Makefile ]; then
        ${YY_MAKE} clean
    fi
    rm -rf ./*
    ${YY_CMAKE} ${YY_CMAKE_OPTIONS}
    ${YY_MAKE} all || exit 1
}

echo "\nyy_test"
build_target ../yy_test/build
make install || exit 1

echo "\nyy_tp_util"
build_target ../../yy_tp_util/build
make install || exit 1

echo "\nyy_cpp"
build_target ../../yy_cpp/build
make install || exit 1

echo "\nyy_json"
build_target ../../yy_json/build
make install || exit 1

echo "\nyy_maths"
build_target ../../yy_maths/build
make install || exit 1

echo "\nyy_mqtt"
build_target ../../yy_mqtt/build
make install || exit 1

echo "\nyy_values"
build_target ../../yy_values/build
make install || exit 1

echo "\nmendel"
build_target ../../mendel/build-dir
