#!/bin/sh

set -e

. ./build_config

echo "\nyy_test"
cd ../yy_test/build
${YY_MAKE} all install || exit 1

echo "\nyy_tp_util"
cd ../../yy_tp_util/build
${YY_MAKE} all install || exit 1

echo "\nyy_cpp"
cd ../../yy_cpp/build
${YY_MAKE} all asan install || exit 1

echo "\nyy_json"
cd ../../yy_json/build
${YY_MAKE} all asan install || exit 1

echo "\nyy_maths"
cd ../../yy_maths/build
${YY_MAKE} all test install || exit 1

echo "\nyy_mqtt"
cd ../../yy_mqtt/build
${YY_MAKE} all asan install || exit 1

echo "\nmendel"
cd ../../mendel/build-dir
${YY_MAKE} all || exit 1
cd ../
